### PR TITLE
Improved usability  of DisconnectReport

### PR DESCRIPTION
**Pull request by vringar**
By allowing the user to specify a name in `generate_report` and add metadata in `add_observation`

Closes #16

### CODE REVIEW

**Review by englehardt — APPROVED** [review]
LGTM. We should bump the version number as well (may as well do that in this PR and I'll cut a new release once we merge it.

@vringar did you get a chance to test these? We should run a quick test before merging.

**Comment by englehardt** [comment]
I'm reminded of #16 which includes some of the domain changes. I think it would be best to pull that into here and tackle all of them at once. See https://github.com/mozilla/trackingprotection-tools/issues/9 for context. As we prep a new report for the redirect trackers we can test all three of these changes (observation metadata, naming, and comments).

**Comment by vringar** [comment]
I merged #16 into this report and wrote some tests to ensure everything is working as expected.

**Review by englehardt — APPROVED** [review]
LGTM. Thanks!

**Comment by englehardt** [comment]
Published this new version to pypi: https://pypi.org/project/trackingprotection-tools/0.5.0/.

**Pull request merged**
